### ISSUE TITLE
Question about the revisor

### ISSUE THREAD

**Issue by lhanchao777** [YiyangZhou/LURE#1]
I have read your paper and it is truly wonderful work! However, I have a question about the revisor. Is the revisor a fine-tuned MiniGPT-4 using the constructed training data in your paper? If so, it seems you have not used any visual information as input when the revisor works. Why not just use a normal LLM?

**Comment by YiyangZhou** [comment]
Thank you for your attention.
The data we used to train the revisor is constructed as described in the paper, which includes a {COCO image, hallucinated description, gold answer}. During training, there is a corresponding image reference for the text. Likewise, when making corrections after training, there is also a corresponding image input.

**Comment by YiyangZhou** [comment]
> Thank you for your attention.
> The data we used to train the revisor is constructed as described in the paper, which includes a {COCO image, hallucinated description, gold answer}. During training, there is a corresponding image reference for the text. Likewise, when making corrections after training, there is also a corresponding image input.

Thank you for your attention.
The data we used to train the revisor is constructed as described in the paper, which includes a {COCO image, hallucinated description, gold answer}. During training, there is a corresponding image reference for the text. Likewise, when making corrections after training, there is also a corresponding image input.

**Comment by YiyangZhou** [comment]
> I have read your paper and it is truly wonderful work! However, I have a question about the revisor. Is the revisor a fine-tuned MiniGPT-4 using the constructed training data in your paper? If so, it seems you have not used any visual information as input when the revisor works. Why not just use a normal LLM?

Thank you for your attention.
The data we used to train the revisor is constructed as described in the paper, which includes a {COCO image, hallucinated description, gold answer}. During training, there is a corresponding image reference for the text. Likewise, when making corrections after training, there is also a corresponding image input.
