### ISSUE TITLE
MINIGPT4 revisor checkpoint release

### ISSUE THREAD

**Issue by JaniceLC** [YiyangZhou/LURE#2]
Hi, guys,

Thank you for providing the clean codes for your amazing method of mitigating hallucination in VLM. I am wondering if it is possible that you could also provide the weights of the revisor. 

Thank you very much!

**Comment by YiyangZhou** [comment]
> of the revisor

Very sorry for such a late reply. I thought I uploaded the weights earlier, I provided the ckpt of the revisor we trained based on MiniGPT-4 7B on hugging face.
