### ISSUE TITLE
Hallucination dataset release

### ISSUE THREAD

**Issue by garyfanhku** [YiyangZhou/LURE#3]
Hi Yiyang, 

Amazing work! As mentioned in your paper, to train the hallucination revisor, we randomly selected 5000 image-text pairs from LLaVA-150k to construct the hallucination dataset to fine-tune an LVLM and use it as a revisor. I am wondering if it is possible for you to share the above-constructed hallucination dataset.

**Comment by YiyangZhou** [comment]
> Hi Yiyang,
> 
> Amazing work! As mentioned in your paper, to train the hallucination revisor, we randomly selected 5000 image-text pairs from LLaVA-150k to construct the hallucination dataset to fine-tune an LVLM and use it as a revisor. I am wondering if it is possible for you to share the above-constructed hallucination dataset.

The specific dataset is provided in the dataset folder.
