### ISSUE TITLE
code for evaluating CHAIR on the dataset

### ISSUE THREAD

**Issue by Maxlinn** [YiyangZhou/LURE#4]
hi zhou and the team, thanks for bringing about LURE!

in the paper, LURE used CHAIR-s and CHAIR-i as the main metric to evaluate hallucinations. i'm interested in calculating CHAIR on my own outputs, but the repos seem not hosting the code.

could you please sharing what code do you use for evaluating CHAIR? thanks a lot!

**Comment by Linxi-ZHAO** [comment]
hi, have you solved this problem?

**Comment by YiyangZhou** [comment]
> hi, have you solved this problem?



> hi zhou and the team, thanks for bringing about LURE!
> 
> in the paper, LURE used CHAIR-s and CHAIR-i as the main metric to evaluate hallucinations. i'm interested in calculating CHAIR on my own outputs, but the repos seem not hosting the code.
> 
> could you please sharing what code do you use for evaluating CHAIR? thanks a lot!

I'm very sorry for such a late reply, we have provided a process for calculating CHAIR metrics based on the original repository: https://github.com/LisaAnne/Hallucination.
