### ISSUE TITLE
Implement of get output probabilities.

### ISSUE THREAD

**Issue by isruihu** [YiyangZhou/LURE#5]
```
To output probabilities, we modify the generation/utils.py file in the Transformers library to generate probabilities for each token.
```
Hi authors, I want to know how you change the transformers/utils to get the out probabilities. Can you release the implements?

Thanks!

**Comment by YiyangZhou** [comment]
I apologize for the late response. We have provided tools for outputting probabilities, and a tutorial is provided in the readme file.

**Comment by YiyangZhou** [comment]
> ```
> To output probabilities, we modify the generation/utils.py file in the Transformers library to generate probabilities for each token.
> ```
> 
> Hi authors, I want to know how you change the transformers/utils to get the out probabilities. Can you release the implements?
> 
> Thanks!

I apologize for the late response. We have provided tools for outputting probabilities, and a tutorial is provided in the readme file.
