### ISSUE TITLE
Problems to reproduce the LURE output

### ISSUE THREAD

**Issue by Linxi-ZHAO** [YiyangZhou/LURE#6]
Hi, great work! 
Thanks for releasing the checkpoints. But I found problems in reproducing the LURE corrections of Minigpt-4 hallucinated generation using generate_IDK.py and output_LURE.py. The LURE outputs are quite bad:(
Could you please provide the sample of caption_file.jsonl, caption_file.jsonl, output.jsonl for reference?
btw, check your codes again lol (typos).

**Comment by gzcch** [comment]
Thank you for the feedback. We have made modifications to the original code, integrating both inference and rewrite into the output_LURE.py.

**Comment by Linxi-ZHAO** [comment]
Thank you for your update.
